services:
  web:
    build:
      .
    container_name: causal-inference-web
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
